GET http://localhost:5000/ad

###

GET http://localhost:5000/ad/10

###

GET http://localhost:5000/ad/category/10

###

POST http://localhost:5000/ad
Content-Type: application/json

{
  "title": "Appartement à louer - Nice",
  "description": "Charmant appartement 2 pièces à louer à Nice, proche du centre-ville.",
  "owner": "info@locationnice.com",
  "price": 1200,
  "picture": "https://cdn.pixabay.com/photo/2016/11/29/12/54/home-1867187_1280.jpg",
  "location": "Nice",
  "category": { "id": 12 },
  "tags": [{ "id": 15 }]
}

###

DELETE http://localhost:5000/ad/37
Content-Type: application/json

###

PUT http://localhost:5000/ad/38
Content-Type: application/json

{
    "title": "Turbo bike V3465",
    "description": "My turbo bike is red, working fine. I'm selling it because I've got a new one",
    "owner": "turbo95@gmail.com",
    "price": 1000000,
    "picture": "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Marseille",
    "category": { "id": 5 }
}

###

PATCH http://127.0.0.1:5000/ad/36
Content-Type: application/json

{
  "title": "Mon vier le vélo"
}

